### PR TITLE
Wiptofiximportofcostumes

### PR DESCRIPTION
**Pull request by ndukwec**

### CODE REVIEW

**Comment by ndukwec** [comment]
This has the export STL function

**Comment by bbabbitt2003** [comment]
Does it work for you? And if it does, how do you get it to work.

 

Bill

**Comment by ndukwec** [comment]
It downloads the file but there are no vertices in it, perhaps because the canvas was not a 3D enabled one so we agreed to push it up to try it with the Anishinaabe Arc project which seems to have a 3D canvas already enabled. You can pull that branch and try it out. I do know that It won't break CSnap though, you can look through the code I added.

**Comment by ndukwec** [comment]
Oh and this commit also has the fix I made to allow access to preloaded costumes, that was worked on before the 3D stuff.

**Pull request merged**
